spring:
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false
        auto-startup: true
    # RabbitMQ via localhost with guest account
    host: localhost
    username: guest
    password: guest
    virtual-host: /ocm
    # RabbitMQ via dev server with dev account
    #host: 172.32.255.90
    #username: rabbitmq
    #password: Ea23jgcx3PeSsCg
    #virtual-host: /geodev
    port: 5672
    api-port: 15672
rabbitmq:
  endpoint: http://127.0.0.1:15672/
  adminusername: guest
  adminpassword: guest
  virtual-host: 0
queue:
  use:
    rabbit: true